server:
  port: 8090
  tomcat:
    max-http-post-size: 70MB

spring:
  application:
    name: usuarios

springdoc:
  swagger-ui:
    path: /documentacion


management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE




